//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
    
    public partial class Flat_Value_tbl
    {
        public int FV_ID { get; set; }
        public Nullable<decimal> Flate_Value { get; set; }
        public Nullable<decimal> Flat_Value_Threshold { get; set; }
        public Nullable<decimal> Flat_Value_Percentage { get; set; }
    }

