//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
    
    public partial class Flat_Rate_tbl
    {
        public int FR_ID { get; set; }
        public Nullable<decimal> Flate_Rate { get; set; }
    }

