//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxDBEntities : DbContext
    {
        public TaxDBEntities()
            : base("name=TaxDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flat_Rate_tbl> Flat_Rate_tbl { get; set; }
        public virtual DbSet<Flat_Value_tbl> Flat_Value_tbl { get; set; }
        public virtual DbSet<Postal_Code_tbl> Postal_Code_tbl { get; set; }
        public virtual DbSet<Progressive_Rate_tbl> Progressive_Rate_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tax_Calculation_Type> Tax_Calculation_Type { get; set; }
        public virtual DbSet<Tax_Payable> Tax_Payable { get; set; }
    }

