//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    using System;
    using System.Collections.Generic;
    
    public partial class Progressive_Rate_tbl
    {
        public int PR_ID { get; set; }
        public Nullable<decimal> From_Amt { get; set; }
        public Nullable<decimal> To_Amt { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }

